spring:
  cache:
#    cache-names: Customer
#   type: simple
#   type: redis
    type: jcache
    jcache:
      provider: org.ehcache.jsr107.EhcacheCachingProvider
      config: classpath:ehcache.xml

#org.slf4j.simpleLogger.defaultLogLevel: trace
#    cache-names=customers
#    type=none
#redis:
#   host: localhost
#   port: 6379

logging.level:
  org.springframework.aop.interceptor.PerformanceMonitorInterceptor: TRACE




